782 add label interpolation option
fepegar/torchio pull request #791
Opened 2022-01-19 23:27 UTC by snavalm

Fixes #782.

**Description**
Adds label_interpolation parameter in spatial augmentations and transforms

**Checklist**

- [x] I have read the [`CONTRIBUTING`](https://github.com/fepegar/torchio/blob/main/CONTRIBUTING.rst) docs and have a developer setup (especially important are `pre-commit`and `pytest`)
- [x] Non-breaking change (would not break existing functionality)
- [ ] Breaking change (would cause existing functionality to change)
- [ ] Tests added or modified to cover the changes
- [x] Integration tests passed locally by running `pytest`
- [x] In-line docstrings updated
- [ ] Documentation updated, tested running `make html` inside the `docs/` folder
- [x] This pull request is ready to be reviewed
- [ ] If the PR is ready and there are multiple commits, I have [squashed them and force-pushed](https://www.w3docs.com/snippets/git/how-to-combine-multiple-commits-into-one-with-3-steps.html#force-pushing-commits-7)

2022-01-20 08:57 UTC, romainVala reviewed
Looks good to me !
thanks for making it 

I think you also need to change the Doc at least in Doc/source/transforms/transforms.rst (line 178)

2022-01-20 18:18 UTC, fepegar requested changes

2022-01-20 18:18 UTC, fepegar commented on torchio/transforms/augmentation/spatial/random_elastic_deformation.py
> +        label_interpolation: See :ref: Interpolation`.
I think a backtick is missing here.

2022-01-21 09:41 UTC, fepegar commented
@snavalm could you modify the docs as suggested by @romainVala?

2022-01-21 12:25 UTC, snavalm commented
Hi, sorry for the delay with this, I am off this week, I will try to do
this early next week



On Fri, 21 Jan 2022, 10:41 Fernando Pérez-García, ***@***.***>
wrote:

> @snavalm <https://github.com/snavalm> could you modify the docs as
> suggested by @romainVala <https://github.com/romainVala>?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/fepegar/torchio/pull/791#issuecomment-1018342175>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AIQTXCELHQXF5OL6C6EKJUTUXES47ANCNFSM5MLIIZ5A>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-01-24 20:39 UTC, fepegar requested changes
Could you please address https://github.com/fepegar/torchio/pull/791#issuecomment-1018342175?

2022-01-24 20:54 UTC, snavalm commented
> ** fepegar ** request

Apologies,this is my first PR, trying to figure how to modify the docs... any pointers? I did `make html` as suggested here [https://github.com/fepegar/torchio/blob/main/CONTRIBUTING.rst](url), what should I do next?

2022-01-24 22:42 UTC, fepegar approved these changes
Thanks! This looks good. I will maybe add some minor changes and merge.

2022-01-24 23:39 UTC, merged

2022-01-24 23:40 UTC, fepegar commented
Many thanks for your contribution, @snavalm! May I add you to the contributors list?

2022-01-25 06:46 UTC, snavalm commented
Yes, please and thanks!

On Mon, 24 Jan 2022, 23:40 Fernando Pérez-García, ***@***.***>
wrote:

> Many thanks for your contribution, @snavalm <https://github.com/snavalm>!
> May I add you to the contributors list?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/fepegar/torchio/pull/791#issuecomment-1020661261>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AIQTXCG5BYMZG7XXGPPAEQLUXXPOHANCNFSM5MLIIZ5A>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-01-25 09:39 UTC, fepegar commented
@all-contributors please add @snavalm for code